# Generated by Django 5.1.15 on 2026-06-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='gpt-4o-mini', max_length=64)),
                ('max_tokens_per_request', models.PositiveIntegerField(default=4096)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('public_signup_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'platform settings',
                'verbose_name_plural': 'platform settings',
            },
        ),
    ]
