# Generated by Django 5.1.15 on 2026-06-01 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_encrypted', models.TextField()),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('google_email', models.EmailField(max_length=254)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_sync_error', models.TextField(blank=True)),
                ('last_sync_summary', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveFolderSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_folder_id', models.CharField(max_length=255)),
                ('drive_folder_name', models.CharField(max_length=512)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_selections', to='sources.googledriveconnection')),
            ],
        ),
        migrations.CreateModel(
            name='DriveSyncedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=255)),
                ('modified_time', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('index_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('index_error', models.TextField(blank=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_modified_time', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_files', to='sources.googledriveconnection')),
                ('folder_selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_files', to='sources.googledrivefolderselection')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='googledrivefolderselection',
            constraint=models.UniqueConstraint(fields=('connection', 'drive_folder_id'), name='unique_folder_per_connection'),
        ),
        migrations.AddIndex(
            model_name='drivesyncedfile',
            index=models.Index(fields=['connection', 'is_deleted'], name='sources_dri_connect_bade9b_idx'),
        ),
        migrations.AddIndex(
            model_name='drivesyncedfile',
            index=models.Index(fields=['connection', 'index_status'], name='sources_dri_connect_2645ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivesyncedfile',
            constraint=models.UniqueConstraint(fields=('connection', 'drive_file_id'), name='unique_drive_file_per_connection'),
        ),
        migrations.AddIndex(
            model_name='googledriveoauthstate',
            index=models.Index(fields=['created_at'], name='sources_goo_created_3d0a81_idx'),
        ),
    ]
