# Generated by Django 5.1.15 on 2026-06-01 08:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.drivesyncedfile')),
            ],
            options={
                'ordering': ['synced_file_id', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw_idx', opclasses=['vector_cosine_ops']), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='rag_documen_search__0a0cea_gin')],
                'constraints': [models.UniqueConstraint(fields=('synced_file', 'chunk_index'), name='unique_chunk_per_document')],
            },
        ),
    ]
